version: 0.2

env:
  parameter-store:
    PORT: "/${APP_ENV}/mobile-app-api/PORT"
    DB_USERNAME: "/${APP_ENV}/mobile-app-api/DB_USERNAME"
    DB_PASSWORD: "/${APP_ENV}/mobile-app-api/DB_PASSWORD"
    DB_DATABASE: "/${APP_ENV}/mobile-app-api/DB_DATABASE"
    DB_HOST: "/${APP_ENV}/mobile-app-api/DB_HOST"
    DB_PORT: "/${APP_ENV}/mobile-app-api/DB_PORT"
    TWILIO_ACCOUNT_SID: "/${APP_ENV}/mobile-app-api/TWILIO_ACCOUNT_SID"
    TWILIO_AUTH_TOKEN: "/${APP_ENV}/mobile-app-api/TWILIO_AUTH_TOKEN"
    TWILIO_FROM_NUMBER: "/${APP_ENV}/mobile-app-api/TWILIO_FROM_NUMBER"
    JWT_SECRET: "/${APP_ENV}/mobile-app-api/JWT_SECRET"
    GOOGLE_CLIENT_ID: "/${APP_ENV}/mobile-app-api/GOOGLE_CLIENT_ID"
    CYPHER_KEY: "/${APP_ENV}/mobile-app-api/CYPHER_KEY"
    RESET_PASSWORD_TEMPLATE_ID: "/${APP_ENV}/mobile-app-api/RESET_PASSWORD_TEMPLATE_ID"
    SEND_GRID_FROM_EMAIL: "/${APP_ENV}/mobile-app-api/SEND_GRID_FROM_EMAIL"
    SEND_GRID_FROM_NAME: "/${APP_ENV}/mobile-app-api/SEND_GRID_FROM_NAME"
    SENDGRID_API_KEY: "/${APP_ENV}/mobile-app-api/SENDGRID_API_KEY"
    PASSWORD_RESET_URL: "/${APP_ENV}/mobile-app-api/PASSWORD_RESET_URL"
    USER_BUCKET_NAME: "/${APP_ENV}/mobile-app-api/USER_BUCKET_NAME"
    AWS_REGION: "/${APP_ENV}/mobile-app-api/AWS_REGION"
    FIREBASE_KEY: "/${APP_ENV}/mobile-app-api/FIREBASE_KEY"
    DOCUMENT_BUCKET_NAME: "/${APP_ENV}/mobile-app-api/DOCUMENT_BUCKET_NAME"
    IMAGE_BUCKET_NAME: "/${APP_ENV}/mobile-app-api/IMAGE_BUCKET_NAME"
    GOOGLE_CLIENT_ID_IOS: "/${APP_ENV}/mobile-app-api/GOOGLE_CLIENT_ID_IOS"
    APPLE_CLIENT_ID: "/${APP_ENV}/mobile-app-api/APPLE_CLIENT_ID"
    VERIFY_EMAIL_URL: "/${APP_ENV}/mobile-app-api/VERIFY_EMAIL_URL"
    WEB_API_KEY: "/${APP_ENV}/mobile-app-api/WEB_API_KEY"
    DELETE_INTERVAL: "/${APP_ENV}/mobile-app-api/DELETE_INTERVAL"
    AWS_PIPELINE_ID: "/${APP_ENV}/mobile-app-api/AWS_PIPELINE_ID"
    TRANSCODER_REGION: "/${APP_ENV}/mobile-app-api/TRANSCODER_REGION"
    AWS_TRANSCODER_BUCKET: "/${APP_ENV}/mobile-app-api/AWS_TRANSCODER_BUCKET"
    TRENDING_EXPIRY_DAY: "/${APP_ENV}/mobile-app-api/TRENDING_EXPIRY_DAY"
    ENV: "/${APP_ENV}/mobile-app-api/ENV"
    REPORT_QUESTION_TEMPLATE_ID: "/${APP_ENV}/mobile-app-api/REPORT_QUESTION_TEMPLATE_ID"
    REPORT_QUESTION_URL: "/${APP_ENV}/mobile-app-api/REPORT_QUESTION_URL"
    ELASTIC_NODE_URL: "/${APP_ENV}/mobile-app-api/ELASTIC_NODE_URL"
    OS_CONNECTION_STRING: "/${APP_ENV}/mobile-app-api/OS_CONNECTION_STRING"
    CLOUD_ID: "/${APP_ENV}/mobile-app-api/CLOUD_ID"
    ELASTIC_USERNAME: "/${APP_ENV}/mobile-app-api/ELASTIC_USERNAME"
    ELASTIC_PASSWORD: "/${APP_ENV}/mobile-app-api/ELASTIC_PASSWORD"
    ELASTIC_QUESTIONS_INDEX: "/${APP_ENV}/mobile-app-api/ELASTIC_QUESTIONS_INDEX"
    ELASTIC_USERS_INDEX: "/${APP_ENV}/mobile-app-api/ELASTIC_USERS_INDEX"
    REPORT_USER_THRESHOLD: "/${APP_ENV}/mobile-app-api/REPORT_USER_THRESHOLD"
    SEND_REPORTED_USER_TEMPLATE_ID: "/${APP_ENV}/mobile-app-api/SEND_REPORTED_USER_TEMPLATE_ID"
    ADMIN_EMAIL: "/${APP_ENV}/mobile-app-api/ADMIN_EMAIL"
    POLL_STEP_FUNCTION_ARN: "/${APP_ENV}/mobile-app-api/POLL_STEP_FUNCTION_ARN"
    VERIFY_EMAIL_TEMPLATE_ID: "/${APP_ENV}/mobile-app-api/VERIFY_EMAIL_TEMPLATE_ID"
    SEND_OTP_TEMPLATE_ID: "/${APP_ENV}/mobile-app-api/SEND_OTP_TEMPLATE_ID"
    ID_MERIT_BASE_URL: "/${APP_ENV}/mobile-app-api/ID_MERIT_BASE_URL"
    ID_MERIT_TOKEN: "/${APP_ENV}/mobile-app-api/ID_MERIT_TOKEN"

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing
  build:
    commands:
      - ls
      - echo "Inserting values into .env file"
      - cp .env.example .env
      - sed -i "s/^DB_USERNAME=/DB_USERNAME=$DB_USERNAME/g" .env
      - sed -i "s/^DB_PASSWORD=/DB_PASSWORD=$DB_PASSWORD/g" .env
      - sed -i "s/^DB_DATABASE=/DB_DATABASE=$DB_DATABASE/g" .env
      - sed -i "s/^DB_HOST=/DB_HOST=$DB_HOST/g" .env
      - sed -i "s/^DB_PORT=/DB_PORT=$DB_PORT/g" .env
      - sed -i "s/^PORT=/PORT=$PORT/g" .env
      - sed -i "s/^JWT_SECRET=/JWT_SECRET=$JWT_SECRET/g" .env
      - sed -i "s/^TWILIO_ACCOUNT_SID=/TWILIO_ACCOUNT_SID=$TWILIO_ACCOUNT_SID/g" .env
      - sed -i "s/^TWILIO_AUTH_TOKEN=/TWILIO_AUTH_TOKEN=$TWILIO_AUTH_TOKEN/g" .env
      - sed -i "s/^TWILIO_FROM_NUMBER=/TWILIO_FROM_NUMBER=$TWILIO_FROM_NUMBER/g" .env
      - sed -i "s/^GOOGLE_CLIENT_ID=/GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID/g" .env
      - sed -i "s/^CYPHER_KEY=/CYPHER_KEY=$CYPHER_KEY/g" .env
      - sed -i "s/^RESET_PASSWORD_TEMPLATE_ID=/RESET_PASSWORD_TEMPLATE_ID=$RESET_PASSWORD_TEMPLATE_ID/g" .env
      - sed -i "s/^SEND_GRID_FROM_EMAIL=/SEND_GRID_FROM_EMAIL=$SEND_GRID_FROM_EMAIL/g" .env
      - sed -i "s/^SEND_GRID_FROM_NAME=/SEND_GRID_FROM_NAME=$SEND_GRID_FROM_NAME/g" .env
      - sed -i "s/^SENDGRID_API_KEY=/SENDGRID_API_KEY=$SENDGRID_API_KEY/g" .env
      - sed -i "s|^PASSWORD_RESET_URL=|PASSWORD_RESET_URL=$PASSWORD_RESET_URL|g" .env
      - sed -i "s/^USER_BUCKET_NAME=/USER_BUCKET_NAME=$USER_BUCKET_NAME/g" .env
      - sed -i "s/^AWS_REGION=/AWS_REGION=$AWS_REGION/g" .env
      - sed -i "s/^DOCUMENT_BUCKET_NAME=/DOCUMENT_BUCKET_NAME=$DOCUMENT_BUCKET_NAME/g" .env
      - sed -i "s/^IMAGE_BUCKET_NAME=/IMAGE_BUCKET_NAME=$IMAGE_BUCKET_NAME/g" .env
      - sed -i "s|^GOOGLE_CLIENT_ID_IOS=|GOOGLE_CLIENT_ID_IOS=$GOOGLE_CLIENT_ID_IOS|g" .env
      - sed -i "s/^APPLE_CLIENT_ID=/APPLE_CLIENT_ID=$APPLE_CLIENT_ID/g" .env
      - sed -i "s|^VERIFY_EMAIL_URL=|VERIFY_EMAIL_URL=$VERIFY_EMAIL_URL|g" .env
      - sed -i "s/^WEB_API_KEY=/WEB_API_KEY=$WEB_API_KEY/g" .env
      - sed -i "s/^DELETE_INTERVAL=/DELETE_INTERVAL=$DELETE_INTERVAL/g" .env
      - sed -i "s/^AWS_PIPELINE_ID=/AWS_PIPELINE_ID=$AWS_PIPELINE_ID/g" .env
      - sed -i "s/^TRANSCODER_REGION=/TRANSCODER_REGION=$TRANSCODER_REGION/g" .env
      - sed -i "s/^AWS_TRANSCODER_BUCKET=/AWS_TRANSCODER_BUCKET=$AWS_TRANSCODER_BUCKET/g" .env
      - sed -i "s/^TRENDING_EXPIRY_DAY=/TRENDING_EXPIRY_DAY=$TRENDING_EXPIRY_DAY/g" .env
      - sed -i "s/^ENV=/ENV=$ENV/g" .env
      - sed -i "s/^REPORT_QUESTION_TEMPLATE_ID=/REPORT_QUESTION_TEMPLATE_ID=$REPORT_QUESTION_TEMPLATE_ID/g" .env
      - sed -i "s|^REPORT_QUESTION_URL=|REPORT_QUESTION_URL=$REPORT_QUESTION_URL|g" .env
      - sed -i "s|^ELASTIC_NODE_URL=|ELASTIC_NODE_URL=$ELASTIC_NODE_URL|g" .env
      - sed -i "s|^OS_CONNECTION_STRING=|OS_CONNECTION_STRING=$OS_CONNECTION_STRING|g" .env
      - sed -i "s|^CLOUD_ID=|CLOUD_ID=$CLOUD_ID|g" .env
      - sed -i "s/^ELASTIC_USERNAME=/ELASTIC_USERNAME=$ELASTIC_USERNAME/g" .env
      - sed -i "s/^ELASTIC_PASSWORD=/ELASTIC_PASSWORD=$ELASTIC_PASSWORD/g" .env
      - sed -i "s/^ELASTIC_QUESTIONS_INDEX=/ELASTIC_QUESTIONS_INDEX=$ELASTIC_QUESTIONS_INDEX/g" .env
      - sed -i "s/^ELASTIC_USERS_INDEX=/ELASTIC_USERS_INDEX=$ELASTIC_USERS_INDEX/g" .env
      - sed -i "s/^REPORT_USER_THRESHOLD=/REPORT_USER_THRESHOLD=$REPORT_USER_THRESHOLD/g" .env
      - sed -i "s/^SEND_REPORTED_USER_TEMPLATE_ID=/SEND_REPORTED_USER_TEMPLATE_ID=$SEND_REPORTED_USER_TEMPLATE_ID/g" .env
      - sed -i "s/^ADMIN_EMAIL=/ADMIN_EMAIL=$ADMIN_EMAIL/g" .env
      - sed -i "s|^POLL_STEP_FUNCTION_ARN=|POLL_STEP_FUNCTION_ARN=$POLL_STEP_FUNCTION_ARN|g" .env
      - sed -i "s|^VERIFY_EMAIL_TEMPLATE_ID=|VERIFY_EMAIL_TEMPLATE_ID=$VERIFY_EMAIL_TEMPLATE_ID|g" .env
      - sed -i "s/^SEND_OTP_TEMPLATE_ID=/SEND_OTP_TEMPLATE_ID=$SEND_OTP_TEMPLATE_ID/g" .env
      - sed -i "s|^ID_MERIT_BASE_URL=|ID_MERIT_BASE_URL=$ID_MERIT_BASE_URL|g" .env
      - sed -i "s|^ID_MERIT_TOKEN=|ID_MERIT_TOKEN=$ID_MERIT_TOKEN|g" .env
      - sed -i "s/^FIREBASE_KEY=*//g" .env
      - echo $'\n'"FIREBASE_KEY=$FIREBASE_KEY" >> .env
      - echo "Installing source NPM dependencies"
      - npm install --quiet
      - npm install --unsafe-perm --quiet
      - echo "Execute Sequelize Database migrations"
      - npx sequelize-cli db:migrate
  post_build:
    commands:
      - echo Build completed on `date`
cache:
  paths:
    - "node_modules/**/*"
artifacts:
  files:
    - "**/*"
